---
services: docker

dist: trusty

env:
  - TEST_SUITE=jessie
  - TEST_SUITE=centos6

script:
  # Run tests.
  - ${PWD}/tests/run_tests_${TEST_SUITE}.sh -v

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
